@startuml
'https://plantuml.com/class-diagram

 class Resume {
    private final String uuid;
    private final String fullName;
    private final EnumMap<ContactType, String> contacts
    private final EnumMap<SectionType, AbstractSection> sections
     getUuid()
     getFullName()
     equals(Object o)
     hashCode()
     toString()
}

 Resume  *-- ContactType : композиция
 enum ContactType{
     TEL
     SKYPE
     MAIL
     LINKEDLN
     GITHUB
     STACKOVERFLOW
     private String title
      ContactType(String title)
      getTitle()
 }

Resume  *-- SectionType : композиция
 enum SectionType{
      PERSONAL
      OBJECTIVE
      ACHIEVEMENT
      QUALIFICATIONS
      EXPERIENCE
      EDUCATION
      private String title
       ContactType(String title)
       getTitle()
 }

Resume  *--  AbstractSection : композиция
     abstract class AbstractSection {
         private final EnumMap<JobName, TextListSection> experienceSection
         private final EnumMap<Education, TextSection> educationSection
    }

AbstractSection <|-- TextSection : extends
class TextSection {
      private String textSection
}

AbstractSection <|-- TextListSection : extends
class TextListSection {
    private final List<String> textListSection
}

AbstractSection  *--  JobName : композиция
enum JobName {
    JAVAONLINEPROJECTS
    WRIKE
    RITCENTER
    LUXOFT
    YOTA
    ENKATA
    SIEMENSAG
    ALCATEL
    private String title
    JobName(String title)
    public String getTitle()
}

AbstractSection  *--  Education : композиция
enum Education {
    COURSERA
    LUXOFT
    SIEMENSAG
    ALCATEL
    SPBNIUITMO
    SCHOOL
    private String title;
    Education(String title)
    getTitle()
 }
@enduml