@startuml
'https://plantuml.com/class-diagram
   Resume  *--  ResumeText
 class Resume {
    private final String uuid;
    private final String fullName;
    private final EnumMap<ContactType, String> contacts
    private final EnumMap<SectionType, ResumeText> sections
     getUuid()
     getFullName()
     equals(Object o)
     hashCode()
     toString()
}

 Resume  *-- ContactType
 enum ContactType{
     TEL
     SKYPE
     MAIL
     LINKEDLN
     GITHUB
     STACKOVERFLOW
     private String title
     ContactType(String title)
     getTitle()
 }

Resume  *-- SectionType
 enum SectionType{
      PERSONAL
      OBJECTIVE
      ACHIEVEMENT
      QUALIFICATIONS
      EXPERIENCE
      EDUCATION
       private String title
           ContactType(String title)
           getTitle()
 }

     class ResumeText {
        private String text;
        private final List<String> sectionText
    }
@enduml